name : Generate Podcasts Feeds
on : [push]
jobs :  
  build :
    runs-on: ubantu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Runs Feed Generator 
        uses: Pavanteja-26/podcast-generator@main
