name : Generate Podcasts Feeds
on : [push]
jobs :  
  build :
    runs-on: ubantu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: setup Python 
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m install --upgrade pip 
          pip install pyyaml
      - name: Run Feed Generator 
        run: python feed.py
      - name: push Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified feed "
          git push 
